name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install angular for get current version info
      run: apt-get install npm && npm install -g @angular/cli:latest
    - name: build docker   
      run: docker build . -t weisserdev/angular:$(date +%s)