name: ci

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '0 1 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: apt-get install npm && npm install -g @angular/cli:latest
      run: docker build . -t weisserdev/angular:$(date +%s)