name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install angular for get current version info
      run: curl --silent "https://api.github.com/repos/angular/angular-cli/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
    - name: build docker   
      run: docker build . -t weisserdev/angular:$(date +%s)