name: ci

on:
  schedule:
      interval: "daily"

jobs:
  docker:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: docker_build
      run: docker build . -t weisserdev/angular

    